Adding back the script

diff --git a/.github/workflows/new_examples_links_in_table_of_content.yml b/.github/workflows/new_examples_links_in_table_of_content.yml
--- a/.github/workflows/new_examples_links_in_table_of_content.yml
+++ b/.github/workflows/new_examples_links_in_table_of_content.yml
@@ -21,32 +21,30 @@ jobs:
           NEW_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
           README: examples/README.md
         run: |
-          echo "$NEW_FILES";
-          # if [[ -f new_example_files.txt ]]; then
-          #   all_linked=true
-          #   while IFS= read -r file; do
-          #     # Get the directory of the new example file
-          #     example_dir=$(dirname "$file")
-          #     # Get the filename without the directory path
-          #     filename=$(basename "$file")
+          all_linked=true
+          for file in ${ALL_CHANGED_FILES}; do
+            echo "$file was added"
+            # Get the directory of the new example file
+            example_dir=$(dirname "$file")
+            # Get the filename without the directory path
+            filename=$(basename "$file")
 
-          #     # Check if link exists in examples/README.md 
-          #     if ! grep -q "$file" examples/README.md && ! grep -q "${file/examples\//](}" examples/README.md; then
-          #       # Check if a README.md exists in the sub-folder, and if so, check for the link there
-          #       if [[ -f "$example_dir/README.md" ]]; then
-          #         if ! grep -q "$filename" "$example_dir/README.md" && ! grep -q "$filename" "$example_dir/README.md"; then
-          #           all_linked=false
-          #           echo "Link to '$file' not found in examples/README.md or $example_dir/README.md"
-          #           echo "::warning file=$file::Link to '$file' not found in a README.md, please add one"
-          #         fi
-          #       else
-          #         all_linked=false
-          #         echo "Link to '$file' not found in examples/README.md, and no README.md found in $example_dir"
-          #         echo "::warning file=$file::Link to '$file' not found in examples/README.md, please add one (or create a README.md in the sub-folder)"
-          #       fi
-          #     fi
-          #   done < new_example_files.txt
-          #   if ! $all_linked; then
-          #     exit 1
-          #   fi
-          # fi
+            # Check if link exists in $README 
+            if ! grep -q "$file" "$README" && ! grep -q "${file/examples\//](}" "$README"; then
+              # Check if a README.md exists in the sub-folder, and if so, check for the link there
+              if [[ -f "$example_dir/README.md" ]]; then
+                if ! grep -q "$filename" "$example_dir/README.md" && ! grep -q "$filename" "$example_dir/README.md"; then
+                  all_linked=false
+                  echo "Link to '$file' not found in "$README".md or $example_dir/README.md"
+                  echo "::warning file=$file::Link to '$file' not found in a README.md, please add one"
+                fi
+              else
+                all_linked=false
+                echo "Link to '$file' not found in $README, and no README.md found in $example_dir"
+                echo "::warning file=$file::Link to '$file' not found in $README, please add one (or create a README.md in the sub-folder)"
+              fi
+            fi
+          done
+          if ! $all_linked; then
+            exit 1
+          fi
