Trying to make it more generic

diff --git a/.github/workflows/new_examples_links_in_table_of_content.yml b/.github/workflows/new_examples_links_in_table_of_content.yml
--- a/.github/workflows/new_examples_links_in_table_of_content.yml
+++ b/.github/workflows/new_examples_links_in_table_of_content.yml
@@ -7,6 +7,8 @@ on:
 jobs:
   new-example-links-in-examples-readme:
     runs-on: ubuntu-latest
+    env:
+      FOLDER: examples
     steps:
       - name: Checkout Code
         uses: actions/checkout@v3
@@ -15,39 +17,39 @@ jobs:
         uses: tj-actions/changed-files@v45
         with:
           files:  |
-            examples/**/*.ipynb
+            "$FOLDER/**/*.ipynb"
       - name: Check README links
         env:
           # We only want the added file so that if we do an exception we dop not have to make an exception again each time qu're editing the file
           NEW_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
-          README: examples/README.md
+          README: "$FOLDER/README.md"
         run: |
           all_linked=true
           for file in ${NEW_FILES}; do
             echo "$file was added"
-            # Get the directory of the new example file
-            example_dir=$(dirname "$file")
+            # Get the directory of the new notebook file
+            notebook_dir=$(dirname "$file")
             # Get the filename without the directory path
             filename=$(basename "$file")
 
             # Check if link exists in $README 
-            if ! grep -q "$file" "$README" && ! grep -q "${file/examples\//](}" "$README"; then
+            if ! grep -q "$file" "$README" && ! grep -q "${file/$$FOLDER\//](}" "$README"; then
               # Check if a README.md exists in the sub-folder, and if so, check for the link there
-              if [[ -f "$example_dir/README.md" ]]; then
-                if ! grep -q "$filename" "$example_dir/README.md" && ! grep -q "$filename" "$example_dir/README.md"; then
+              if [[ -f "$notebook_dir/README.md" ]]; then
+                if ! grep -q "$filename" "$notebook_dir/README.md"; then
                   all_linked=false
-                  echo "Link to '$file' not found in "$README".md or $example_dir/README.md"
+                  echo "  Link to '$file' not found in "$README".md or $notebook_dir/README.md"
                   echo "::warning file=$file::Link to '$file' not found in a README.md, please add one"
                 else
-                  echo "Link to '$file' found in $example_dir/README.md"
+                  echo "  Link to '$file' found in $notebook_dir/README.md"
                 fi
               else
                 all_linked=false
-                echo "Link to '$file' not found in $README, and no README.md found in $example_dir"
+                echo "  Link to '$file' not found in $README, and no README.md found in $notebook_dir"
                 echo "::warning file=$file::Link to '$file' not found in $README, please add one (or create a README.md in the sub-folder)"
               fi
             else
-              echo "Link to '$file' found in $README"
+              echo "  Link to '$file' found in $README"
             fi
           done
           if ! $all_linked; then
